org: ag94570
app: aws-python-starter-lambda
service: python-starter-lambda-function

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  environment:
      STAGE: ${opt:stage, 'dev'}

functions:
  firstLambda:
    handler: starterLambda/firstLambda.handler
